project_id = "jiopyrhuanoeshscxzvc"

[functions.reset-password]
verify_jwt = false

[functions.check-email-allowed]
verify_jwt = false

[functions.notify-workout]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.admin-data]
verify_jwt = false